perf:
 - name: "RAID_PI_PTS"
   label: "PORT_NAME"
   target: "PORT"
   type: ""
 - name: "RAID_PI_PRCS"
   label: "ADAPTOR_ID,PROCESSOR_ID"
   target: "PRCS"
   type: ""
 - name: "RAID_PI"
   label: "ALL"
   target: "CACHE"
   type: ""
 - name: "RAID_PI_PLS"
   label: "POOL_ID"
   target: "POOL"
   type: ""
 - name: "RAID_PI_LDS"
   label: "LDEV_NUMBER"
   target: "LDEV"
   type: ""
 - name: "RAID_PI_LDA"
   label: "INPUT_RECORD_TYPE"
   target: "SYSTEM"
   type: ""
 - name: "RAID_PI_RGS"
   label: "RAID_GROUP_NUMBER"
   target: "RGS"
   type: ""
 - name: "RAID_PI_CHS"
   label: "CHA_NAME"
   target: "CHS"
   type: ""
capacity:
 - name: "RAID_PD_VVTC"
   label: "TIER_NUMBER,TIER_TYPE"
   target: "TIER"
   type: "LDEV"
 - name: "RAID_PD_VVF"
   label: "PARTITION_NUMBER"
   target: "PART"
   type: "LDEV"
 - name: "RAID_PD_VVC"
   label: ""
   target: "ALL"
   type: "LDEV"
 - name: "RAID_PD_PLTC"
   label: "TIER_NUMBER,TIER_TYPE"
   target: "TIER"
   type: "POOL"
 - name: "RAID_PD_PLF"
   label: "PARTITION_NUMBER"
   target: "PART"
   type: "POOL"
 - name: "RAID_PD_PLC"
   label: ""
   target: "ALL"
   type: "POOL"
